### ISSUE TITLE
Error when run gulp

### ISSUE THREAD

**Issue by korcstar** [ci-blox/Ignition-Go#10]
I got error when try to run gulp
Please check attached file and give me solution
![gulp-error](https://cloud.githubusercontent.com/assets/13351126/22921956/b6925b18-f2d6-11e6-94ff-867b7c7e530d.png)

**Comment by korcstar** [comment]
I got solution
I install lots of another modules
Please update description to install project

**Comment by boblennes** [comment]
You just needed to do bower install and npm install, right?
