### ISSUE TITLE
Installation wizard... How?

### ISSUE THREAD

**Issue by Romerski** [ci-blox/Ignition-Go#11]
Hi, how can I run installation wizard? I've done all steps and I have ignition-go folder on "C:\xampp\htdocs\myigosite" but when I access to "localhost/myigosite/install/init" it returns error 404. Neither http://localhost:8080/install/init

Any help? Thanks

**Comment by bayuly94** [comment]
use virtualhost

2017-05-31 22:14 GMT+07:00 Yeray Romero <notifications@github.com>:

**Comment by Romerski** [comment]
Ok, now is working...just had to change database config file.
