### ISSUE TITLE
Is ACL included?

### ISSUE THREAD

**Issue by handoyo** [ci-blox/Ignition-Go#19]
Hi, is ACL included in this framework? Thanks for the great framework by the way.

**Comment by boblennes** [comment]
If by ACL you mean basic permssions and roles, then yes, see the securinator module under igocore/ in Ignition Go.  It's fairly basic but should do the trick for most needs.  Basically, users can have a user role which can be tied to permissions.  Then the permissions which can be referenced in your code to control access to different function..  see the auth library for what methods are available.

Here is one you would most certainly use:
public function has_permission($permission, $role_id = null, $override = false)

If by ACL you are referring to Unix/Linux folder and file permssions, then no on that one.

**Comment by handoyo** [comment]
Yes on the permissions and roles. I will look at the auth. Thanks for the explanation. Btw do you have any showcase what kind of applications that has been made by using this framework?

**Comment by boblennes** [comment]
Great!  We do not have a showcase yet, but do send me a note when yours is completed!  Here is one app that is built on Ignition Go for reference: 
[GoTickets on Codester link](https://www.codester.com/items/4512/go-tickets-ticket-management-system?ref=visualsol)

**Comment by boblennes** [comment]
I'll also try to add a document on permissions and roles next week.

**Comment by handoyo** [comment]
That would be great. Will wait for permissions and roles documentation. Thanks

**Comment by boblennes** [comment]
Fyi we now autoadd permissions for blox modules if that helps..

**Comment by boblennes** [comment]
@handoyo please see new doc [ACL - Users, Roles and Permissions](http://ci-blox.github.io/Ignition-Go/DocACL.html)

**Comment by handoyo** [comment]
Are you referring to this link
http://ci-blox.github.io/Ignition-Go/#/concepts/ACL? I can't open your
link.Says Page not found.

**Comment by boblennes** [comment]
Yep, sorry I moved it and combined it into the new master documentation just after I sent the old link..
