### ISSUE TITLE
Time of the build really long with Gulp

### ISSUE THREAD

**Issue by AlfioSaitta** [ci-blox/Ignition-Go#2]
Since more than 12 hours yet the build phase with gulp was not completed

`root:/srv/ignition/gulpfile.js# ps -eo pid,cmd,etime | grep gulp`

> 9462 gulp                           12:19:03

The current status after 12 hours:
`root:/srv/ignition# gulp`

> [22:33:47] Using gulpfile /srv/ignition/gulpfile.js
> [22:33:47] Starting 'default'...
> [22:33:47] Starting 'build'...
> [22:33:47] Starting 'clean'...
> [22:33:47] Finished 'clean' after 28 ms
> [22:33:47] Starting 'copy:fonts'...
> [22:33:47] Finished 'copy:fonts' after 14 ms
> [22:33:47] Starting 'copy:scripts'...
> [22:33:47] Finished 'copy:scripts' after 518 μs
> [22:33:47] Starting 'copy'...
> [22:33:47] Finished 'copy' after 15 μs
> [22:33:47] Starting 'images'...
> [22:33:47] Starting 'cssmin:frontend'...
> [22:33:47] Starting 'cssmin:admin'...
> [22:33:47] Starting 'uglify:frontend'...
> [22:33:47] Starting 'uglify:admin'...
> [22:33:47] gulp-imagemin: Minified 0 images
> [22:33:47] Finished 'images' after 68 ms
> [22:33:49] Finished 'cssmin:frontend' after 1.96 s
> [22:33:49] Finished 'cssmin:admin' after 1.95 s
> [22:33:49] Starting 'cssmin'...
> [22:33:49] Finished 'cssmin' after 7.25 μs
> [22:33:49] Finished 'uglify:admin' after 1.94 s
> [22:33:49] Finished 'uglify:frontend' after 1.94 s
> [22:33:49] Starting 'uglify'...
> [22:33:49] Finished 'uglify' after 7.94 μs
> [22:33:49] Finished 'build' after 2.02 s
> [22:33:49] Starting 'watch'...
> [10:06:58] Starting 'uglify:frontend'...
> [10:06:58] Starting 'uglify:admin'...
> [10:06:58] Starting 'cssmin:admin'...
> [10:06:58] Starting 'cssmin:frontend'...
> [10:06:58] Finished 'uglify:admin' after 35 ms
> [10:06:58] Starting 'watch:js-admin'...
> [10:06:58] Finished 'watch:js-admin' after 34 μs
> [10:06:58] Finished 'cssmin:admin' after 74 ms
> [10:06:58] Starting 'watch:css-admin'...
> [10:06:58] Finished 'watch:css-admin' after 24 μs
> [10:06:58] Finished 'cssmin:frontend' after 68 ms
> [10:06:58] Starting 'watch:css-frontend'...
> [10:06:58] Finished 'watch:css-frontend' after 27 μs
> [10:07:00] Finished 'uglify:frontend' after 1.43 s
> [10:07:00] Starting 'watch:js-frontend'...
> [10:07:00] Finished 'watch:js-frontend' after 22 μs

**Comment by boblennes** [comment]
After the initial run, just before the Starting 'watch'... step, the build is complete.  But the 'Starting 'watch'...' step runs the whole time so for example if you make a css change it will automatically minify immediately.

**Comment by AlfioSaitta** [comment]
You can see the result here: http://ignition.collateral-studios.com/

**Comment by boblennes** [comment]
This is a separate issue...
Please verify /igocore/models/settings_model.php exists.   I use windows so perhaps it needs to be renamed to /igocore/models/Settings_model.php

**Comment by AlfioSaitta** [comment]
Yes, right.... fixed :+1:

**Comment by AlfioSaitta** [comment]
Another issue..... Error 404 page not found on http://ignition.collateral-studios.com/Admin/check/login

**Comment by boblennes** [comment]
I couldn't duplicate right away, so I suspect it's an upper/lowercase issue somewhere.  I'm reinstalling a new installation right now to make sure there's not a file missing in the github repository.

**Comment by boblennes** [comment]
I made some updates, can you pull and let me know if it's working.  The 404 is definitely related to upper/lowercase.

**Comment by AlfioSaitta** [comment]
Won't work

**Comment by boblennes** [comment]
found it, try latest.

**Comment by AlfioSaitta** [comment]
Now no errors, i just had to rename a file

`root:/srv/ignition/igocore/models# mv settings_model.php Settings_model.php`

**Comment by AlfioSaitta** [comment]
If you want, I can give you access to the web space of my server and you can work directly on linux machine.

**Comment by boblennes** [comment]
All working now?   If you want, send access info to email
" admin at ciblox,com ".
