### ISSUE TITLE
Missing bootstrap css and js file after install

### ISSUE THREAD

**Issue by handoyo** [ci-blox/Ignition-Go#20]
Hi, after i install the framework and run the application. I get 404 error message regarding the missing bootstrap css and js file. I have followed the tutorials by using nodejs and gulp. Please advise. Btw i'm using windows 10. Thanks.

**Comment by boblennes** [comment]
Hi,  assuming you ran the bower steps correctly, from the command prompt just run "gulp build" to  build/move the files to the right place, or "gulp serve" to build and launch a browser session.  There's also a tutorial at Codementor https://www.codementor.io/community/topic/ignition-go

**Comment by handoyo** [comment]
I will give it a try again today. Thanks

**Comment by handoyo** [comment]
Hi, I tried "gulp build". I get these errors when i open the main page.

![image](https://user-images.githubusercontent.com/225439/31324406-4de230fa-acdc-11e7-8be9-d1c2a5e2f2d4.png)

**Comment by boblennes** [comment]
what output do you get for 'gulp build'?  it should not have errors.  output should be like this:
 **/c/xampp/htdocs/ignition-go$ gulp build**
`[21:27:09] Using gulpfile C:\xampp7\htdocs\ignition-go\gulpfile.js`
`[21:27:09] Starting 'build'...`
`[21:27:09] Starting 'clean'...`
`[21:27:09] Finished 'clean' after 38 ms`
`[21:27:09] Starting 'copy:fonts'...`
`[21:27:09] Finished 'copy:fonts' after 14 ms`
[21:27:09] Starting 'copy:scripts'...
`[21:27:09] Finished 'copy:scripts' after 299 μs`
`[21:27:09] Starting 'copy'...`
`[21:27:09] Finished 'copy' after 1.58 μs`
[21:27:09] Starting 'cssmin:frontend'...
[21:27:09] Starting 'cssmin:admin'...
[21:27:09] Starting 'uglify:frontend'...
[21:27:09] Starting 'uglify:admin'...
[21:27:13] Finished 'cssmin:frontend' after 3.22 s
[21:27:13] Finished 'uglify:frontend' after 3.57 s
[21:27:13] Finished 'cssmin:admin' after 3.83 s
[21:27:13] Starting 'cssmin'...
[21:27:13] Finished 'cssmin' after 2.77 μs
[21:27:13] Finished 'uglify:admin' after 3.83 s
[21:27:13] Starting 'uglify'...
[21:27:13] Finished 'uglify' after 1.98 μs
[21:27:13] Finished 'build' after 3.91 s
`

**Comment by handoyo** [comment]
This is the output:

![image](https://user-images.githubusercontent.com/225439/31330202-8c2060c8-ad07-11e7-8bbf-1846eedc4841.png)

**Comment by boblennes** [comment]
I added a change for the bower step to resolve a version conflict - do a git pull or get the new bower.json.
Delete your public/components folder.
Do the 'bower install' step - use powershell or cmd if Windows.
Then do gulp step again.

**Comment by handoyo** [comment]
Ok, I will download the bower.json file and do the gulp again. Will let you know the result.

**Comment by handoyo** [comment]
There are no more bootstrap.min.css error message,but still get the bootstrap.min.js and app.min.js 404 error message.

![image](https://user-images.githubusercontent.com/225439/31332388-68d5c780-ad10-11e7-932d-405cbed7f89e.png)

**Comment by boblennes** [comment]
Also looks like latest admin-lte moved some things..  we'll need to adjust those too, to the new locations.

**Comment by handoyo** [comment]
How can i help?

**Comment by boblennes** [comment]
We need to change the gulp config file to:
1. separate out jquery.min.js and bootstrap.min.js (move these to copy step)
2. correct admin-lte references and remove jquery-legacy
3. change the 3 master templates accordingly.

I can do this tommorow if you can wait.

**Comment by handoyo** [comment]
Yes i can wait for tomorrow. Thank you

**Comment by boblennes** [comment]
Pull the latest... let us know if all is well.

**Comment by handoyo** [comment]
Ok, i will let you know the result.

**Comment by handoyo** [comment]
I still get these:

![image](https://user-images.githubusercontent.com/225439/31373368-053f4f3e-adc4-11e7-8a42-2df969b4af31.png)

**Comment by boblennes** [comment]
Get the latest...
EITHER Delete your public/components folder and do the 'bower install' step 
OR do bower install --f 
...Then do gulp build or gulp serve step.
(We now removed some files that were blocking bower's default behavior.)

Now all should work great!

**Comment by handoyo** [comment]
I have followed your instructions and use a virtual host too, yet i still get these errors:

![image](https://user-images.githubusercontent.com/225439/31419096-f7ebeffe-ae63-11e7-8a3a-9df4742a3ab5.png)

I'm going to try the quickstart version.

**Comment by boblennes** [comment]
From your error message, I can see you did.not get the latest commits.  The app min.js file is now named  frontend.min.js.  You can use quickstart  branch but it needs to be updated for latest components.

**Comment by handoyo** [comment]
I just download the latest files, re run the steps. And i get these message on the frontend:

![image](https://user-images.githubusercontent.com/225439/31420533-503e0946-ae6c-11e7-90c6-4f878fff8671.png)

And these on the admin side:

![image](https://user-images.githubusercontent.com/225439/31420558-76cf575e-ae6c-11e7-8e16-bbced4dea57f.png)

**Comment by boblennes** [comment]
line 59 of the gulp config should be:
				dir_bower + '/bootstrap/dist/css/bootstrap.min.css'				
but copy step is not copying also, I fixed that now too.
And there were still AdminLTE changes needed and now done.
Thanks for your help, try now!

**Comment by handoyo** [comment]
Thanks, remains the font-awesome error:

![image](https://user-images.githubusercontent.com/225439/31479209-e19b78fa-af3f-11e7-9091-edeb402329b7.png)

Thanks for the quick fix too.

**Comment by boblennes** [comment]
I guess the fontawesome font files are expected to be in /font-awesome/ but we dont want that,,, Add the following line to .htaccess around line 143:

`redirect /font-awesome/ /assets/`

Update: this is now in github.

**Comment by boblennes** [comment]
Let me know if not ok or ok, then we can close this.

**Comment by handoyo** [comment]
Hi, sorry for late reply. I just redownload the most current files and it works as expected. Thanks for the help and i will close this.
