### ISSUE TITLE
The QuickStart version doesn't contain dependencies

### ISSUE THREAD

**Issue by axoloth** [ci-blox/Ignition-Go#23]
I install the quickStart version but it seems to be the same as the master:
The front-end appears, but no database was create and no dependencies were includes.
If i call the url /install/init the screen ask me to run bower and gulp.
![ignition](https://user-images.githubusercontent.com/8740682/33395477-efdf2cc8-d545-11e7-8962-8b2a7eeb4534.JPG)

**Comment by boblennes** [comment]
For the quickstart branch, only the js files and css files are installed but not bower, npm, and gulp itself.
You should be able to run if you create the database (or is the installer preventing you from doing that step?)  You may also run the install.sql file manually.  Let me know if you are still missing some files after that.

**Comment by axoloth** [comment]
All is OK.
Thanks !
