### ISSUE TITLE
Cannot install the latest version

### ISSUE THREAD

**Issue by handoyo** [ci-blox/Ignition-Go#24]
Hi, i've downloaded the master version. Try to install it on local machine, and i get 

![image](https://user-images.githubusercontent.com/225439/34098409-d10d51f8-e40e-11e7-91f3-988008be48e4.png)

I don't get any error if i run the sql via PhpMyadmin. I'm using Php 7.1.7. I have followed the install steps btw. What should i do to fix it? Thanks..

**Comment by jhunieray** [comment]
Same with mine. What I did is I manually run the install.sql in my SQL server.

**Comment by handoyo** [comment]
@jhunieray Can you get the application run now?

**Comment by boblennes** [comment]
I am seeing a problem with MariaDB - it didnt support the AUTO_INCREMENT in the CREATE TABLE, it seems you need to do a separate ALTER TABLE.

**Comment by boblennes** [comment]
html

**Comment by jhunieray** [comment]
@handoyo Yeah sure

**Comment by boblennes** [comment]
the actual issue is mysqli and db->query - we need to run one CREATE TABLE at a time in a loop..

**Comment by boblennes** [comment]
@handoyo, this is now fixed in master [a66942f501a055cc8a0bae5e1f3580fecd709d97](https://github.com/ci-blox/Ignition-Go/commit/a66942f501a055cc8a0bae5e1f3580fecd709d97)

**Comment by handoyo** [comment]
Sorry for late reply, i will try it again. Thanks for the fix
