### ISSUE TITLE
Switch from NPM and Bower to Yarn

### ISSUE THREAD

**Issue by boblennes** [ci-blox/Ignition-Go#25]
Need to move on from using NPM and Bower to just use Yarn.

**Comment by boblennes** [comment]
This is mostly, if not totally, complete.

**Comment by Kr3m** [comment]
I 2nd that.  NPM is just a pain in the ass.  I'm glad yarn is working.

**Comment by boblennes** [comment]
I think Yarn is working totally, is that your experience as well?

**Comment by Kr3m** [comment]
@boblennes  Yarn is absolutely working.  The only issues I've run into so far, I mentioned in another report.  It has more to do with the model's  file name generating with a lowercase name as well as the admin folder that goes with a module being named "Admin" which is inaccessible by default until you rename it.  Also, it seems authenticated controllers are not working properly.

**Comment by boblennes** [comment]
We are using Yarn so closed this old issue.
