### ISSUE TITLE
Blox Errors and no table created

### ISSUE THREAD

**Issue by jkkenzie** [ci-blox/Ignition-Go#26]
I got the following error: (written on Public.php)
Message:  Undefined variable: createSave
Filename: files/controller.php
Line Number: 316

Also: Admin Backend does not give the option to edit blox module.
        ** Alot of things dont work on admin backend and also the URL to admin is not /Admin or /somethingeasy

**Comment by boblennes** [comment]
Is this error in the module builder generated output?

________________________________

**Comment by jkkenzie** [comment]
Yes, actually 5000 lines of errors wrapped in html tags on the controllers generated by the builder.

**Comment by jkkenzie** [comment]
Let me give you a preview of the file:
`
			<\p style="margin-left:10px"\>
			File: .......\public\index.php<\br /\>
			Line: 393<\br /\>
			Function: require_once			<\/p\>

		
	

<\/div\><\?php defined('BASEPATH') || exit('No direct script access allowed');

/**
 * Public controller
 * @created on : 
 * @author :
 * Copyright {year}
 *
 */
class Public extends 
{`

**Comment by jkkenzie** [comment]
You can see the Class extends nothing and a lot of html before the class declaration...

**Comment by jkkenzie** [comment]
Hope this list of errors helps resolve the issue: 
Message:  Undefined variable: constructorRestrict,
Message:  Undefined variable: baseClass
Message:  Undefined variable: mb_save
Message:  Undefined variable: mb_edit
Message:  Undefined variable: mb_create
Message:  Undefined variable: constructorExtras
Message:  Undefined variable: loadModel
Message:  Undefined variable: textarea_included
Message:  Array to string conversion, Filename: files/controller.php, Line Number: 493
Message:  Undefined variable: db_field_type
Message:  Undefined variable: datetime_included
Message:  Undefined variable: jQueryUI

**Comment by boblennes** [comment]
All these errors were caused by an extra ; when we added a sample ajax controller - try now.

**Comment by jkkenzie** [comment]
Trying shortly

**Comment by jkkenzie** [comment]
I tried and the errors are gone but the table was not created. And the views files of the module are blank (edit, listing & create).

One controller called "Public" seems to have an error because we are using PHP keyword for the name of the class... 
`/**
 * Public controller
 * @created on : 
 * @author :
 * Copyright {year}
 *
 */
class Public extends Admin_Controller`

**Comment by boblennes** [comment]
The 'Public' should be the name of the module.  The migration is not running to create the table... can you try creating the table first and do "create from existing"?  the migration logic needs rewriting I think and might take a day or 2.

**Comment by jkkenzie** [comment]
Noted. I think that works for now.. Keep improving though

**Comment by boblennes** [comment]
I fixed the name for the public controller now.

**Comment by jkkenzie** [comment]
great! would test it

**Comment by jkkenzie** [comment]
Now working without errors. Just make the Adminlte template on the backend look nice.. the module builder is ugly! :) Its seems the template has not been set with proper css and js resources as well html itself. The menu expand collapse feature and where you place the Admin menu items... Looks incomplete...

**Comment by boblennes** [comment]
the DB migration logic was added for blox modules now.

**Comment by boblennes** [comment]
Let me know if all errors are gone now, then I'll fix cosmetics.

**Comment by jkkenzie** [comment]
I didn't get any error. everything smooth.
