### ISSUE TITLE
Where are the change password / register new user etc.

### ISSUE THREAD

**Issue by robkampen** [ci-blox/Ignition-Go#30]
I have installed and got it working - I cannot say "all working", as many of the items mentioned in the README are not there and certainly do not function.
Reading the documents gave me to believe that this takes up from where bonfire left off - very disappointed, bonfire does way more out of the box, stuff I do not wish to code and develop - like auth and registration and user management - all of which bonfire does quite well, saves me lots of work.
Ignition-Go should be Ignition-Pause-not-yet-ready-to-go
Also the yarn install does little, I needed to download the zip file and unpack into the document root - so install instructions need work too.
Pity, I thought the upgrades to bootstrap and jquery etc would be worth having and hence spent time going after this only to find it is only a shell. Fortunately bonfire 0.84 with codeigniter 3.1.8 is simple to achieve.
Wish you all the best, and suggest you alter your definition of the project to reflect actual deliverable and not a wish list of what might be possible.

**Comment by boblennes** [comment]
It shouldn't be too hard to build upon the user module that is included.  Certainly there is much to be done.. I would love if we could bring this project to have the full set of features that Bonfire had, the difference being that many would be 'Blox' so you could pick and choose what you need,  I do feel we have a solid foundation.   But the lack of contributions from anyone else has kept this project from reaching its potential.  Please consider contributing something.  Let me know if I can point you to something- anything in the documents is there, but the UI might need to have a button/screen etc to demonstrate it...

**Comment by boblennes** [comment]
I've added a project (see reference) to add the missing views for "Forgot Password" and "Register".

**Comment by boblennes** [comment]
Forgot Password has been added.

**Comment by boblennes** [comment]
The register URL is /register - the register submit does not seem to be working, so we'll look into that.
