### ISSUE TITLE
PHP Mcrypt Extension

### ISSUE THREAD

**Issue by artlantis** [ci-blox/Ignition-Go#32]
As you might know, in Php 7.2 edition, Mcrypt deprecated so Ingition-Go can't go next step in install. I did some research on internet for windows edition of the extension but no success. If it's not mandatory, could you please remove from installation?

**Comment by boblennes** [comment]
Yes, we will need to remove this.  I believe it (mcrypt) was originally included for a CodeIgniter fallback option in system/core/Security.php ~line 632, but is not used anywhere else.  I will take it out of the required extension list, we can also replace the CI reference if needed.

**Comment by boblennes** [comment]
@artlantis I removed this requirement in the installer.  Can you do a pull and check that the installer runs as expected for you now? 
Thanks!

**Comment by artlantis** [comment]
Ok, I didn't see any issue.
