### ISSUE TITLE
Modules Folder

### ISSUE THREAD

**Issue by artlantis** [ci-blox/Ignition-Go#34]
Just for curiosity, is there any reason to move `/modules` folder from `application/modules` to `igocore/modules`?

In `readme.md` file, you specified `/modules` folder under the `application` but there is only `api` available, the others reside in `igocore/modules`.

**Comment by boblennes** [comment]
igocore/modules is reserved for default Ignition Go modules.  application/modules should always be used, and you can override all or parts of any IGO module there.

**Comment by artlantis** [comment]
Thanks.
