### ISSUE TITLE
Module Creation

### ISSUE THREAD

**Issue by Kr3m** [ci-blox/Ignition-Go#35]
@boblennes 

I've noticed some minor issues in Module creation (especially pertaining to unix based case sensitive systems).  Models for some reason are output with lowercase names, and the folders themselves (mainly module->module_name->Admin are written with uppercase names which both cause errors before renaming.

**Comment by Kr3m** [comment]
@boblennes Sorry one small issue I just noticed on your main page is it says visit us on Gtihub instead of Github on the button.  Not related to the program, but thought I'd mention it.

**Comment by boblennes** [comment]
Hi Kevin, thanks for the feedback.  I use Windows so sorry on the lower/uppercase issues you may be experiencing... I do try to look out for that.  I was out of town for the weekend so sorry for the delayed reply too.  I am the primary maintainer now although occasionally someone supplies a pull request.  I'd love if there are any case issues you fix that you would kindly either share them back or submit a P.R.  I think that controllers are uppercase always but not sure on HMVC modules...

**Comment by Kr3m** [comment]
Yes, both the controllers and models should always be uppercase.  Directories should always be lowercase.  When I get a minute, I'll take a look at the code and see what I can do to patch this up.

**Comment by boblennes** [comment]
Any pull request or code updates?

**Comment by boblennes** [comment]
No response so closing.
