### ISSUE TITLE
Authenticated Controllers

### ISSUE THREAD

**Issue by Kr3m** [ci-blox/Ignition-Go#36]
When I create a module with an admin, public, and authenticated controller, if I go to view that module while I'm signed in, it shows a login button anyway in the upper right as well as a read only view of the module itself (which seems more appropriate for a public view unless of course this is by design).   Regardless of how the module is supposed to display to an authenticated user, it certainly shouldn't be showing a login button that disappears and kicks me back to the home page (as I'm already signed in) when I click on it.

**Comment by boblennes** [comment]
It sounds like maybe your sessions are not set up.  I recommend using database sessions for easiest visibility.
