### ISSUE TITLE
new installation

### ISSUE THREAD

**Issue by chiabgigi** [ci-blox/Ignition-Go#37]
Hello
I'm trying to install ignition go but there are problems
I use php 7.3
I followed the guide
1 I configured virtual host, mine is virtualhost: 8880
2 I fixed IGO_ROUTER (STRPOS) problem, temporarily I posed @ to 'each'
3 I loaded the sql file
4 ... if I go to localhost: 8880 / install / init, page not found (404) appears
how can i install ignition go?
config / config.php file
`$ base_url = 'http: // localhost: 8880';
if (isset ($ _ SERVER ['HTTP_HOST']) && preg_match ('/ ^ (([0-9a-f:] +]) (d {1,3} (d {1 , 3}) {3}) | [a-z0-9 -.] +) (: D +)? $ / I ', $ _SERVER [' HTTP_HOST ']))
{
$ base_url = (is_https ()? 'https':' http ').': //'.$_SERVER ['HTTP_HOST']
.substr ($ _ SERVER ['SCRIPT_NAME'], 0, strpos ($ _ SERVER ['SCRIPT_NAME'], basename ($ _ SERVER ['SCRIPT_FILENAME'])));
}

$ config ['base_url'] = $ base_url;`

**Comment by boblennes** [comment]
We've not yet tried PHP 7.3... use PHP 7.2 instead and see if better results.

**Comment by chiabgigi** [comment]
Thanks for the reply
but I don't think it's the fault of the php version that doesn't installer
in which file is specified installation, php version

**Comment by Volk1nson** [comment]
> Thanks for the reply
> but I don't think it's the fault of the php version that doesn't installer
> in which file is specified installation, php version

Did you managed to solve issue by your self? If yes, can you please give me a clue how. Thanks in advance!

**Comment by boblennes** [comment]
We made the proper HMVC fix for PHP 7.3 in IGO_Router.php.  Please try the development branch.  Also we clarified the install steps in the readme file to be sure.  I can install and run on Windows in XAMPP now using PHP 7.3.*

**Comment by chiabgigi** [comment]
tanks
best regards
