### ISSUE TITLE
Issue with installing on nginx

### ISSUE THREAD

**Issue by prashantsingh0205** [ci-blox/Ignition-Go#38]
I have multiple web apps over my server. so I use nginx and set root folders in config.
**File Structure**
/var/www/html/projname

**nginx block**
location /projname{
            index index.php;
            root /var/www/html/projname/public;
            try_files $uri $uri/ /projname/public/index.php?$args;
        }

When I hit http://domain.tld/projname/install/init
It says, Your Web Root should be set to the public folder,but it's not. It's pointing to the Root folder.
Am I mission something?

**Comment by boblennes** [comment]
I'm sorry but I don't use Nginx so I have no idea.  Try posting to the CodeIgniter slack group or forum maybe?

**Comment by getimecode** [comment]
@prashantsingh0205 Try read about Ngix Server Blocks for more clue https://www.nginx.com/resources/wiki/start/topics/examples/server_blocks/ 
as it note : “VirtualHost” is an Apache term. NGINX does not have Virtual hosts, it has “Server Blocks”
my local VirtualHost config : 
`<VirtualHost *:80>
DocumentRoot "/xampp-7.0.27-0-vc14/htdocs/base/public"
ServerName base
</VirtualHost>
`
you may want to try "Server Blocks" config : 
`
server {
    server_name projname;
    root /var/www/html/projname/public;
  }
`

**Comment by prashantsingh0205** [comment]
Getting the following error when running "gulp serve" or "gulp"
fs.js:27
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (/var/www/html/freshdash/node_modules/natives/index.js:143:24)
    at Object.req [as require]
(/var/www/html/freshdash/node_modules/natives/index.js:55:10)
    at Object.<anonymous>
(/var/www/html/freshdash/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js
(internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)

Configutation
node - 13.1.0
npm - 6.13.6
yarn - 1.21.1

gulp
CLI version: 2.2.0
Local version: 3.9.1

Please help
