### ISSUE TITLE
Performance log [Request]

### ISSUE THREAD

**Issue by jeffersonlicet** [ci-blox/Ignition-Go#7]
Amazing work. I want to use it for an API REST,  how is it performance compared with other micro frameworks like lumen etc..? (Why I would use this? Because ci). Thank you.

**Comment by boblennes** [comment]
It should be fine for most needs, but the API controller is still WIP - but I'll check it in tomorrow for you to try.

**Comment by boblennes** [comment]
I published the base API Controller - let me know if you have any problems.  I'd love to hear ideas for performance tests...

**Comment by boblennes** [comment]
I made some corrections to the API controller and put a sample controller out there.  I used Postman runner with 100 iterations and was getting a 160ms avg response, but I did not have anything set up to compare to.
